package com.aliyun.odps.mma.constant;

import com.aliyun.odps.mma.util.StringUtils;

public enum OssTransferState {
    DATA_INIT,
    SRC_CREATE_EXTERNAL_TABLE_DOING,
    SRC_CREATE_EXTERNAL_TABLE_DONE,
    SRC_CREATE_EXTERNAL_TABLE_FAILED,
    SRC_WRITE_EXTERNAL_TABLE_DOING,
    SRC_WRITE_EXTERNAL_TABLE_DONE,
    SRC_WRITE_EXTERNAL_TABLE_FAILED,
    DST_CREATE_EXTERNAL_TABLE_DOING,
    DST_CREATE_EXTERNAL_TABLE_DONE,
    DST_CREATE_EXTERNAL_TABLE_FAILED,
    DST_ADD_EXTERNAL_PTS_DOING,
    DST_ADD_EXTERNAL_PTS_DONE,
    DST_ADD_EXTERNAL_PTS_FAILED,
    DST_EXTERNAL_TABLE_TO_INNER_TABLE_DOING,
    DST_EXTERNAL_TABLE_TO_INNER_TABLE_DONE,
    DST_EXTERNAL_TABLE_TO_INNER_TABLE_FAILED,
    SRC_DELETE_EXTERNAL_PTS_DOING,
    SRC_DELETE_EXTERNAL_PTS_DONG,
    SRC_DELETE_EXTERNAL_PTS_FAILED,
    DST_DELETE_EXTERNAL_PTS_DOING,
    DST_DELETE_EXTERNAL_PTS_DONE,
    DST_DELETE_EXTERNAL_PTS_FAILED,
    OSS_DELETE_OBJECT_DOING,
    OSS_DELETE_OBJECT_DONE,
    OSS_DELETE_OBJECT_FAILED;

    public static OssTransferState fromString(String state) {
        if (StringUtils.isBlank(state)) {
            return DATA_INIT;
        }

        return OssTransferState.valueOf(state.toUpperCase());
    }
}
